name: Android CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
      - name: Run kover
        run: ./gradlew koverReport
      - name: Upload coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: build/reports/kover/report.xml